"""add pending input state

Revision ID: 1ceed9d6c29f
Revises: e6ebb45c8b39
Create Date: 2026-08-29 13:37:15.000705+00:00
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "1ceed9d6c29f"
down_revision: str | None = "e6ebb45c8b39"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("pending", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "pending")
    # ### end Alembic commands ###
