"""add retry context

Revision ID: 873f2c47f918
Revises: 1ceed9d6c29f
Create Date: 2026-08-29 13:40:55.062444+00:00
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "873f2c47f918"
down_revision: str | None = "1ceed9d6c29f"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("retry_context", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "retry_context")
    # ### end Alembic commands ###
