"""initial schema

Revision ID: e6ebb45c8b39
Revises:
Create Date: 2026-08-28 20:14:03.729483+00:00
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e6ebb45c8b39"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("messenger", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column(
            "tariff", sa.String(length=16), server_default="free", nullable=False
        ),
        sa.Column("referral_code", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("daily_image_quota", sa.Integer(), nullable=False),
        sa.Column("referred_by", sa.BigInteger(), nullable=True),
        sa.Column("bonus_messages", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bonus_images", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tariff_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("bonus_images >= 0", name="ck_users_bonus_images"),
        sa.CheckConstraint("bonus_messages >= 0", name="ck_users_bonus_messages"),
        sa.ForeignKeyConstraint(
            ["referred_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "messenger", "external_id", name="uq_users_messenger_external"
        ),
        sa.UniqueConstraint("referral_code", name="uq_users_referral_code"),
    )
    op.create_table(
        "dialogs",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("turns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_turns", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "referrals",
        sa.Column("referee_id", sa.BigInteger(), nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("referrer_id <> referee_id", name="ck_referrals_no_self"),
        sa.ForeignKeyConstraint(["referee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("referee_id"),
    )
    op.create_table(
        "usage",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("messages_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("images_used", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "day"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage")
    op.drop_table("referrals")
    op.drop_table("dialogs")
    op.drop_table("users")
    # ### end Alembic commands ###
